# Generated by Django 3.0.8 on 2020-07-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200721_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', upload_to='shop/img'),
        ),
        migrations.AddField(
            model_name='products',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
