# Generated by Django 3.0.8 on 2020-07-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200721_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
